/**
 * ExecuteGetSettlementStatement - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteGetSettlementStatement {
    context;
    idGenerator;
    statement;
    constructor(context, idGenerator, statement) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.statement = statement;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.stlId();
        // All field names extracted from OpenAPI spec: none
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.statementId) {
            throw new ValidationError("statementId is required");
        }
        const statementId = input.statementId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.statement.getSettlementStatement({ statementId: statementId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${statementId}`);
        }
        return entity;
    }
}
