/**
 * Routes for Slot
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listInventorySlots, registerInventorySlot } from "../handlers/slot.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function slotRoutes(fastify: FastifyInstance) {
  // GET /v1/inventory/slots (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/inventory/slots",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInventoryDependenciesForRequest();
        await listInventorySlots(request, reply, deps);
      });
    }
  );


  // POST /v1/inventory/slots (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/inventory/slots",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInventoryDependenciesForRequest();
        await registerInventorySlot(request, reply, deps);
      });
    }
  );


}
