/**
 * ExecuteGetCampaign - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteGetCampaign {
    context;
    idGenerator;
    campaign;
    constructor(context, idGenerator, campaign) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.campaign = campaign;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.cmpId();
        // All field names extracted from OpenAPI spec: none
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.campaignId) {
            throw new ValidationError("campaignId is required");
        }
        const campaignId = input.campaignId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.campaign.getCampaign({ campaignId: campaignId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${campaignId}`);
        }
        return entity;
    }
}
