/**
 * ExecuteListCampaigns - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListCampaigns {
    context;
    idGenerator;
    campaign;
    constructor(context, idGenerator, campaign) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.campaign = campaign;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.cmpId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.campaign.listCampaigns({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
