/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildBiddingDomainModule,
  buildCampaignsDomainModule,
  buildConversionsDomainModule,
  buildDisputesDomainModule,
  buildIdentityDomainModule,
  buildInventoryDomainModule,
  buildReportingDomainModule,
  buildSettlementDomainModule,
} from "../domains/index.js";
import type {
  BiddingDomainModule,
  CampaignsDomainModule,
  ConversionsDomainModule,
  DisputesDomainModule,
  IdentityDomainModule,
  InventoryDomainModule,
  ReportingDomainModule,
  SettlementDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private biddingModule: BiddingDomainModule | null = null;
  private campaignsModule: CampaignsDomainModule | null = null;
  private conversionsModule: ConversionsDomainModule | null = null;
  private disputesModule: DisputesDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private inventoryModule: InventoryDomainModule | null = null;
  private reportingModule: ReportingDomainModule | null = null;
  private settlementModule: SettlementDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get bidding domain module
   */
  getBiddingDependencies(): BiddingDomainModule {
    if (!this.biddingModule) {
      this.biddingModule = buildBiddingDomainModule(this.dynamoClient);
    }
    return this.biddingModule;
  }

  /**
   * Get campaigns domain module
   */
  getCampaignsDependencies(): CampaignsDomainModule {
    if (!this.campaignsModule) {
      this.campaignsModule = buildCampaignsDomainModule(this.dynamoClient);
    }
    return this.campaignsModule;
  }

  /**
   * Get conversions domain module
   */
  getConversionsDependencies(): ConversionsDomainModule {
    if (!this.conversionsModule) {
      this.conversionsModule = buildConversionsDomainModule(this.dynamoClient);
    }
    return this.conversionsModule;
  }

  /**
   * Get disputes domain module
   */
  getDisputesDependencies(): DisputesDomainModule {
    if (!this.disputesModule) {
      this.disputesModule = buildDisputesDomainModule(this.dynamoClient);
    }
    return this.disputesModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get inventory domain module
   */
  getInventoryDependencies(): InventoryDomainModule {
    if (!this.inventoryModule) {
      this.inventoryModule = buildInventoryDomainModule(this.dynamoClient);
    }
    return this.inventoryModule;
  }

  /**
   * Get reporting domain module
   */
  getReportingDependencies(): ReportingDomainModule {
    if (!this.reportingModule) {
      this.reportingModule = buildReportingDomainModule(this.dynamoClient);
    }
    return this.reportingModule;
  }

  /**
   * Get settlement domain module
   */
  getSettlementDependencies(): SettlementDomainModule {
    if (!this.settlementModule) {
      this.settlementModule = buildSettlementDomainModule(this.dynamoClient);
    }
    return this.settlementModule;
  }

  clearBiddingDependencies(): void { this.biddingModule = null; }
  clearCampaignsDependencies(): void { this.campaignsModule = null; }
  clearConversionsDependencies(): void { this.conversionsModule = null; }
  clearDisputesDependencies(): void { this.disputesModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearInventoryDependencies(): void { this.inventoryModule = null; }
  clearReportingDependencies(): void { this.reportingModule = null; }
  clearSettlementDependencies(): void { this.settlementModule = null; }

  getBiddingDependenciesForRequest(): BiddingDomainModule {
    return this.getBiddingDependencies();
  }

  getCampaignsDependenciesForRequest(): CampaignsDomainModule {
    return this.getCampaignsDependencies();
  }

  getConversionsDependenciesForRequest(): ConversionsDomainModule {
    return this.getConversionsDependencies();
  }

  getDisputesDependenciesForRequest(): DisputesDomainModule {
    return this.getDisputesDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getInventoryDependenciesForRequest(): InventoryDomainModule {
    return this.getInventoryDependencies();
  }

  getReportingDependenciesForRequest(): ReportingDomainModule {
    return this.getReportingDependencies();
  }

  getSettlementDependenciesForRequest(): SettlementDomainModule {
    return this.getSettlementDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.biddingModule = null;
    this.campaignsModule = null;
    this.conversionsModule = null;
    this.disputesModule = null;
    this.identityModule = null;
    this.inventoryModule = null;
    this.reportingModule = null;
    this.settlementModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
