/**
 * GetActionForecast handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getActionForecast } from "@clearbid/api-server/domains/bidding/handlers";
import type { BiddingDDDDependencies } from "@clearbid/api-server/domains/bidding";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@clearbid/tests/shared";
import { BIDDING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetActionForecast", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: BiddingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<BiddingDDDDependencies>(
      BIDDING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetActionForecast, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { campaignId: entity.id };

    await getActionForecast(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetActionForecast.execute).toHaveBeenCalledWith(expect.objectContaining({ campaignId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { campaignId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetActionForecast, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getActionForecast(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
