/**
 * Campaigns DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Campaigns Domain Module - Composition root
 *
 * DDD: Composition root for campaigns domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CampaignRepositoryAdapter,
  ConversionDefinitionRepositoryAdapter,
} from "@clearbid/adapters/campaigns";
import { getIdGeneratorService } from "@clearbid/adapters";
import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCampaign,
  ExecuteDefineConversionAction,
  ExecuteGetCampaign,
  ExecuteListCampaigns,
} from "@clearbid/services/campaigns/usecases";
// Ports (interfaces)
import type {
  CampaignRepository,
  ConversionDefinitionRepository,
} from "@clearbid/services/campaigns/ports";

export interface CampaignsDomainModule {
  repos: {
    campaigns: CampaignRepository;
    conversionDefinitions: ConversionDefinitionRepository;
  };
  useCases: {
    campaigns: {
      create: ExecuteCreateCampaign;
      get: ExecuteGetCampaign;
      list: ExecuteListCampaigns;
    };
    conversionDefinitions: {
      get: ExecuteDefineConversionAction;
    };
  };
}

export function buildCampaignsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CampaignsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      campaigns?: CampaignRepository;
      conversionDefinitions?: ConversionDefinitionRepository;
    } = {};

    obj.campaigns = new CampaignRepositoryAdapter(dynamoClient);
    obj.conversionDefinitions = new ConversionDefinitionRepositoryAdapter(dynamoClient);
    return {
      campaigns: obj.campaigns!,
      conversionDefinitions: obj.conversionDefinitions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    campaigns: {
      create: new ExecuteCreateCampaign(executionContext, idGenerator, repos.campaigns),
      get: new ExecuteGetCampaign(executionContext, idGenerator, repos.campaigns),
      list: new ExecuteListCampaigns(executionContext, idGenerator, repos.campaigns),
    },
    conversionDefinitions: {
      get: new ExecuteDefineConversionAction(executionContext, idGenerator, repos.conversionDefinitions),
    },
  };
  return { repos, useCases: useCases as CampaignsDomainModule["useCases"] };
}
