/**
 * ActionForecast DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ActionForecast DTOs
 *
 * DDD: Application DTOs for ActionForecast use cases.
 */

import type { GetActionForecastParams } from "@clearbid/core/bidding/types";

export type GetActionForecastInput = GetActionForecastParams;

export type GetActionForecastOutput = {};
