/**
 * BidRequest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BidRequest DTOs
 *
 * DDD: Application DTOs for BidRequest use cases.
 */

import type { SubmitBidRequestRequestInput } from "@clearbid/core/bidding/types";

export type SubmitBidRequestInput = SubmitBidRequestRequestInput;

export type SubmitBidRequestOutput = {};
