/**
 * ListConversion DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListConversionsParams } from "@clearbid/core/conversions";

export function createListConversionRequest(overrides: Partial<ListConversionsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
