/**
 * ListSlot DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListInventorySlotsParams } from "@clearbid/core/inventory";

export function createListSlotRequest(overrides: Partial<ListInventorySlotsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
