/**
 * Dispute Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DisputeEntity } from "@clearbid/core/disputes/models/index.js";
import { disputesSchemas } from "@clearbid/core/disputes";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "dsp";

export function createDispute(overrides: Partial<DisputeEntity> = {}) {
  const raw = {
    id: overrides.id ?? `dsp_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    claim: overrides.claim ?? "shaving",
    conversionId: overrides.conversionId ?? faker.string.uuid(),
    resolutionDeadline: overrides.resolutionDeadline ?? new Date().toISOString(),
    status: overrides.status ?? "open",
    ...overrides,
  };

  return disputesSchemas.Dispute.parse(raw);
}

export function disputeBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDispute(overrides));
}
