/**
 * ConversionDefinition Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ConversionDefinitionEntity } from "@clearbid/core/campaigns/models/index.js";
import { campaignsSchemas } from "@clearbid/core/campaigns";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cmp";

export function createConversionDefinition(overrides: Partial<ConversionDefinitionEntity> = {}) {
  const raw = {
    id: overrides.id ?? `cdf_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    actionType: overrides.actionType ?? "registration",
    attributionWindowHours: overrides.attributionWindowHours ?? faker.number.int(),
    ...overrides,
  };

  return campaignsSchemas.ConversionDefinition.parse(raw);
}

export function conversionDefinitionBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createConversionDefinition(overrides));
}
