/**
 * CostPerActionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CostPerActionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CostPerActionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CostPerActionRepository,
} from "@clearbid/services/reporting";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CostPerActionRepositoryDdb } from "./cost-per-action-repository.ddb.js";

/**
 * CostPerActionRepositoryAdapter
 *
 * Implements CostPerActionRepository port for infrastructure layer.
 */
export class CostPerActionRepositoryAdapter implements CostPerActionRepository {
  private readonly ddb: CostPerActionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CostPerActionRepositoryDdb(this.dynamoClient);
  }

  async getCostPerActionReport(input: Parameters<CostPerActionRepository['getCostPerActionReport']>[0]): Promise<Awaited<ReturnType<CostPerActionRepository['getCostPerActionReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCostPerActionReport(input);
  }
}
