/**
 * CostPerActionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { CostPerActionRepositoryDdb } from "./cost-per-action-repository.ddb.js";
/**
 * CostPerActionRepositoryAdapter
 *
 * Implements CostPerActionRepository port for infrastructure layer.
 */
export class CostPerActionRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new CostPerActionRepositoryDdb(this.dynamoClient);
    }
    async getCostPerActionReport(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getCostPerActionReport(input);
    }
}
