/**
 * ExecuteOpenDispute - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { NotFoundError, ValidationError } from "../errors";
export class ExecuteOpenDispute {
    context;
    idGenerator;
    dispute;
    constructor(context, idGenerator, dispute) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.dispute = dispute;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.dspId();
        // All field names extracted from OpenAPI spec: claim, conversionId, evidence
        // Validate input
        if (!input) {
            throw new ValidationError("Input is required");
        }
        if (!input.conversionId) {
            throw new ValidationError("conversionId is required");
        }
        const conversionId = input.conversionId;
        // Load entity via repository (pass correlation ID for response meta)
        const entity = await this.dispute.openDispute({ conversionId: conversionId, orgId: this.context.getOrgId(), correlationId });
        if (!entity) {
            throw new NotFoundError(`Entity not found: ${conversionId}`);
        }
        return entity;
    }
}
