/**
 * ResolutionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ResolutionRepositoryDdb } from "./resolution-repository.ddb.js";
/**
 * ResolutionRepositoryAdapter
 *
 * Implements ResolutionRepository port for infrastructure layer.
 */
export class ResolutionRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ResolutionRepositoryDdb(this.dynamoClient);
    }
    async resolveDispute(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.resolveDispute(input);
    }
}
