/**
 * Quarantine DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Quarantine DTOs
 *
 * DDD: Application DTOs for Quarantine use cases.
 */

import type { QuarantineInventorySlotParams, QuarantineInventorySlotRequestInput } from "@clearbid/core/inventory/types";

export type QuarantineInventorySlotInput = QuarantineInventorySlotParams & QuarantineInventorySlotRequestInput;

export type QuarantineInventorySlotOutput = {};
