/**
 * Slot DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Slot DTOs
 *
 * DDD: Application DTOs for Slot use cases.
 */

import type { ListInventorySlotsParams, RegisterInventorySlotRequestInput } from "@clearbid/core/inventory/types";

export type ListInventorySlotsInput = ListInventorySlotsParams;

export type RegisterInventorySlotInput = RegisterInventorySlotRequestInput;

export type ListInventorySlotsOutput = {};

export type RegisterInventorySlotOutput = {};
