/**
 * DefineConversionAction handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { defineConversionAction } from "@clearbid/api-server/domains/campaigns/handlers";
import type { CampaignsDDDDependencies } from "@clearbid/api-server/domains/campaigns";
import { createConversionDefinition as createConversionDefinitionEntity } from "@clearbid/factories/campaigns";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@clearbid/tests/shared";
import { CAMPAIGNS_USE_CASES } from "../__factories__/use-cases.js";

describe("DefineConversionAction", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CampaignsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CampaignsDDDDependencies>(
      CAMPAIGNS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createConversionDefinitionEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeDefineConversionAction, "execute").mockResolvedValue(useCaseResult);

    await defineConversionAction(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeDefineConversionAction.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
