/**
 * Conversion DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Conversion DTOs
 *
 * DDD: Application DTOs for Conversion use cases.
 */

import type { AttestConversionRequestInput, ListConversionsParams } from "@clearbid/core/conversions/types";

export type ListConversionsInput = ListConversionsParams;

export type AttestConversionInput = AttestConversionRequestInput;

export type ListConversionsOutput = {};

export type AttestConversionOutput = {};
