/**
 * Verification DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Verification DTOs
 *
 * DDD: Application DTOs for Verification use cases.
 */

import type { GetConversionVerificationParams } from "@clearbid/core/conversions/types";

export type GetConversionVerificationInput = GetConversionVerificationParams;

export type GetConversionVerificationOutput = {};
