/**
 * ConversionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConversionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConversionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConversionRepository,
} from "@clearbid/services/conversions";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConversionRepositoryDdb } from "./conversion-repository.ddb.js";

/**
 * ConversionRepositoryAdapter
 *
 * Implements ConversionRepository port for infrastructure layer.
 */
export class ConversionRepositoryAdapter implements ConversionRepository {
  private readonly ddb: ConversionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConversionRepositoryDdb(this.dynamoClient);
  }

  async listConversions(input: Parameters<ConversionRepository['listConversions']>[0]): Promise<Awaited<ReturnType<ConversionRepository['listConversions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConversions(input);
  }

  async attestConversion(input: Parameters<ConversionRepository['attestConversion']>[0]): Promise<Awaited<ReturnType<ConversionRepository['attestConversion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.attestConversion(input);
  }
}
