/**
 * ConversionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ConversionRepositoryDdb } from "./conversion-repository.ddb.js";
/**
 * ConversionRepositoryAdapter
 *
 * Implements ConversionRepository port for infrastructure layer.
 */
export class ConversionRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ConversionRepositoryDdb(this.dynamoClient);
    }
    async listConversions(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listConversions(input);
    }
    async attestConversion(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.attestConversion(input);
    }
}
