/**
 * VerificationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { VerificationRepositoryDdb } from "./verification-repository.ddb.js";
/**
 * VerificationRepositoryAdapter
 *
 * Implements VerificationRepository port for infrastructure layer.
 */
export class VerificationRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new VerificationRepositoryDdb(this.dynamoClient);
    }
    async getConversionVerification(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getConversionVerification(input);
    }
}
