/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
/**
 * @clearbid/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@clearbid/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@clearbid/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@clearbid/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@clearbid/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@clearbid/core";
 */
// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately
import * as __shared from "./_shared/index.js";
import * as _bidding from "./bidding/index.js";
import * as _campaigns from "./campaigns/index.js";
import * as _conversions from "./conversions/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _inventory from "./inventory/index.js";
import * as _reporting from "./reporting/index.js";
import * as _settlement from "./settlement/index.js";
// Export as namespaces
export const _shared = __shared;
export const bidding = _bidding;
export const campaigns = _campaigns;
export const conversions = _conversions;
export const disputes = _disputes;
export const identity = _identity;
export const inventory = _inventory;
export const reporting = _reporting;
export const settlement = _settlement;
// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@clearbid/core"; activity.types.*
//   - Direct exports: import * from "@clearbid/core/activity/types/index.js"
//   - Direct exports: import * from "@clearbid/core/activity/repositories/index.js"
//   - Direct exports: import * from "@clearbid/core/activity/models/index.js"
//   - Direct exports: import * from "@clearbid/core/activity/value-objects/index.js"
// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export { DOMAIN_PREFIX_MAP, isValidDomainId, extractDomainFromId, } from "./_shared/index.js";
// Bidding Service
export { schemas as BiddingSchemas } from "./bidding/schemas/bidding.schemas.js";
// Campaigns Service
export { schemas as CampaignsSchemas } from "./campaigns/schemas/campaigns.schemas.js";
// Conversions Service
export { schemas as ConversionsSchemas } from "./conversions/schemas/conversions.schemas.js";
// Disputes Service
export { schemas as DisputesSchemas } from "./disputes/schemas/disputes.schemas.js";
// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";
// Inventory Service
export { schemas as InventorySchemas } from "./inventory/schemas/inventory.schemas.js";
// Reporting Service
export { schemas as ReportingSchemas } from "./reporting/schemas/reporting.schemas.js";
// Settlement Service
export { schemas as SettlementSchemas } from "./settlement/schemas/settlement.schemas.js";
