/**
 * Bidding DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Bidding Domain Module - Composition root
 *
 * DDD: Composition root for bidding domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ActionForecastRepositoryAdapter,
  BidRequestRepositoryAdapter,
} from "@clearbid/adapters/bidding";
import { getIdGeneratorService } from "@clearbid/adapters";
import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";

// Ports (interfaces)
import type {
  ActionForecastRepository,
  BidRequestRepository,
} from "@clearbid/services/bidding/ports";

export interface BiddingDomainModule {
  repos: {
    actionForecasts: ActionForecastRepository;
    bidRequests: BidRequestRepository;
  };
  useCases: {

  };
}

export function buildBiddingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): BiddingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      actionForecasts?: ActionForecastRepository;
      bidRequests?: BidRequestRepository;
    } = {};

    obj.actionForecasts = new ActionForecastRepositoryAdapter(dynamoClient);
    obj.bidRequests = new BidRequestRepositoryAdapter(dynamoClient);
    return {
      actionForecasts: obj.actionForecasts!,
      bidRequests: obj.bidRequests!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
  };
  return { repos, useCases: useCases as BiddingDomainModule["useCases"] };
}
