/**
 * CostPerAction DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CostPerAction DTOs
 *
 * DDD: Application DTOs for CostPerAction use cases.
 */

import type { GetCostPerActionReportParams } from "@clearbid/core/reporting/types";

export type GetCostPerActionReportInput = GetCostPerActionReportParams;

export type GetCostPerActionReportOutput = {};
