/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Bidding Domain Use Cases
 * 
 * List of all use case names for the bidding domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const BIDDING_USE_CASES = [
  "executeGetActionForecast",
  "executeSubmitBidRequest"
] as const;
