/**
 * Inventory DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Inventory Domain Module - Composition root
 *
 * DDD: Composition root for inventory domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  QuarantineRepositoryAdapter,
  SlotRepositoryAdapter,
} from "@clearbid/adapters/inventory";
import { getIdGeneratorService } from "@clearbid/adapters";
import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListInventorySlots,
  ExecuteRegisterInventorySlot,
} from "@clearbid/services/inventory/usecases";
// Ports (interfaces)
import type {
  QuarantineRepository,
  SlotRepository,
} from "@clearbid/services/inventory/ports";

export interface InventoryDomainModule {
  repos: {
    quarantines: QuarantineRepository;
    slots: SlotRepository;
  };
  useCases: {
    slots: {
      create: ExecuteRegisterInventorySlot;
      list: ExecuteListInventorySlots;
    };
  };
}

export function buildInventoryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): InventoryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      quarantines?: QuarantineRepository;
      slots?: SlotRepository;
    } = {};

    obj.quarantines = new QuarantineRepositoryAdapter(dynamoClient);
    obj.slots = new SlotRepositoryAdapter(dynamoClient);
    return {
      quarantines: obj.quarantines!,
      slots: obj.slots!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    slots: {
      create: new ExecuteRegisterInventorySlot(executionContext, idGenerator, repos.slots),
      list: new ExecuteListInventorySlots(executionContext, idGenerator, repos.slots),
    },
  };
  return { repos, useCases: useCases as InventoryDomainModule["useCases"] };
}
