/**
 * Handlers for Quarantine
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InventoryDomainModule } from "../dependencies/inventory-ddd.dependencies.js";
import type { QuarantineInventorySlotInput } from "@clearbid/services/inventory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/inventory/slots/{slotId}/quarantine
 * Operation: quarantineInventorySlot
 */
export async function quarantineInventorySlot(
  request: FastifyRequest<{ Params: { slotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InventoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: QuarantineInventorySlotInput = {
    slotId: request.params.slotId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.quarantines.get.execute(input);
  return reply.code(200).send(result);
}


