/**
 * Handlers for Slot
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InventoryDomainModule } from "../dependencies/inventory-ddd.dependencies.js";
import type { ListInventorySlotsInput, RegisterInventorySlotInput } from "@clearbid/services/inventory";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/inventory/slots
 * Operation: listInventorySlots
 */
export async function listInventorySlots(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InventoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListInventorySlotsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.slots.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/inventory/slots
 * Operation: registerInventorySlot
 */
export async function registerInventorySlot(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: InventoryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RegisterInventorySlotInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.slots.create.execute(input);
  return reply.code(201).send(result);
}


