/**
 * ActionForecastRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ActionForecastRepositoryDdb } from "./action-forecast-repository.ddb.js";
/**
 * ActionForecastRepositoryAdapter
 *
 * Implements ActionForecastRepository port for infrastructure layer.
 */
export class ActionForecastRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ActionForecastRepositoryDdb(this.dynamoClient);
    }
    async getActionForecast(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getActionForecast(input);
    }
}
