/**
 * ActionForecastRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ActionForecastRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ActionForecastRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ActionForecastRepository,
} from "@clearbid/services/bidding";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ActionForecastRepositoryDdb } from "./action-forecast-repository.ddb.js";

/**
 * ActionForecastRepositoryAdapter
 *
 * Implements ActionForecastRepository port for infrastructure layer.
 */
export class ActionForecastRepositoryAdapter implements ActionForecastRepository {
  private readonly ddb: ActionForecastRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ActionForecastRepositoryDdb(this.dynamoClient);
  }

  async getActionForecast(input: Parameters<ActionForecastRepository['getActionForecast']>[0]): Promise<Awaited<ReturnType<ActionForecastRepository['getActionForecast']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getActionForecast(input);
  }
}
