/**
 * BidRequestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { BidRequestRepositoryDdb } from "./bid-request-repository.ddb.js";
/**
 * BidRequestRepositoryAdapter
 *
 * Implements BidRequestRepository port for infrastructure layer.
 */
export class BidRequestRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new BidRequestRepositoryDdb(this.dynamoClient);
    }
    async submitBidRequest(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.submitBidRequest(input);
    }
}
