/**
 * BidRequestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BidRequestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BidRequestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BidRequestRepository,
} from "@clearbid/services/bidding";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BidRequestRepositoryDdb } from "./bid-request-repository.ddb.js";

/**
 * BidRequestRepositoryAdapter
 *
 * Implements BidRequestRepository port for infrastructure layer.
 */
export class BidRequestRepositoryAdapter implements BidRequestRepository {
  private readonly ddb: BidRequestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BidRequestRepositoryDdb(this.dynamoClient);
  }

  async submitBidRequest(input: Parameters<BidRequestRepository['submitBidRequest']>[0]): Promise<Awaited<ReturnType<BidRequestRepository['submitBidRequest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitBidRequest(input);
  }
}
