/**
 * Repository interface for ConversionDefinition
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ConversionDefinitionEntity
} from "../models/conversion-definition.entity.js";
import type {
  ConversionDefinition
} from "../types/index.js";
/**
 * ConversionDefinitionRepository Interface
 */
export interface ConversionDefinitionRepository extends CreateReadRepository<ConversionDefinitionEntity, ConversionDefinition, string, Record<string, never>> {

}
