/**
 * Payout DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Payout DTOs
 *
 * DDD: Application DTOs for Payout use cases.
 */

import type { ExecutePublisherPayoutRequestInput } from "@clearbid/core/settlement/types";

export type ExecutePublisherPayoutInput = ExecutePublisherPayoutRequestInput;

export type ExecutePublisherPayoutOutput = {};
