/**
 * Reporting DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reporting Domain Module - Composition root
 *
 * DDD: Composition root for reporting domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CostPerActionRepositoryAdapter,
} from "@clearbid/adapters/reporting";
import { getIdGeneratorService } from "@clearbid/adapters";
import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";

// Ports (interfaces)
import type {
  CostPerActionRepository,
} from "@clearbid/services/reporting/ports";

export interface ReportingDomainModule {
  repos: {
    costPerActions: CostPerActionRepository;
  };
  useCases: {

  };
}

export function buildReportingDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportingDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      costPerActions?: CostPerActionRepository;
    } = {};

    obj.costPerActions = new CostPerActionRepositoryAdapter(dynamoClient);
    return {
      costPerActions: obj.costPerActions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
  };
  return { repos, useCases: useCases as ReportingDomainModule["useCases"] };
}
