/**
 * ConversionDefinition DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConversionDefinition DTOs
 *
 * DDD: Application DTOs for ConversionDefinition use cases.
 */

import type { DefineConversionActionParams, DefineConversionActionRequestInput } from "@clearbid/core/campaigns/types";

export type DefineConversionActionInput = DefineConversionActionParams & DefineConversionActionRequestInput;

export type DefineConversionActionOutput = {};
