/**
 * ExecuteListInventorySlots - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class ExecuteListInventorySlots {
    context;
    idGenerator;
    slot;
    constructor(context, idGenerator, slot) {
        this.context = context;
        this.idGenerator = idGenerator;
        this.slot = slot;
    }
    async execute(input) {
        // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
        const correlationId = this.idGenerator.invId();
        // All field names extracted from OpenAPI spec: none
        // List entities via repository
        const result = await this.slot.listInventorySlots({ ...input, orgId: this.context.getOrgId(), correlationId });
        return result;
    }
}
