/**
 * ExecuteListInventorySlots - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListInventorySlots Use Case
 *
 * DDD: Application use case for list Slot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListInventorySlotsInput, ListInventorySlotsOutput } from "../dto/slot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@clearbid/services/_shared/index.js";
import type { SlotRepository } from "../ports";

export class ExecuteListInventorySlots {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly slot: SlotRepository
  ) {}

  async execute(input: ListInventorySlotsInput): Promise<ListInventorySlotsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.slot.listInventorySlots({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListInventorySlotsOutput;
  }
}
