/**
 * ExecuteRegisterInventorySlot - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterInventorySlot Use Case
 *
 * DDD: Application use case for create Slot.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterInventorySlotInput, RegisterInventorySlotOutput } from "../dto/slot.dto";
import type { ExecutionContextService, IdGeneratorService } from "@clearbid/services/_shared/index.js";
import type { SlotRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterInventorySlot {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly slot: SlotRepository
  ) {}

  async execute(input: RegisterInventorySlotInput): Promise<RegisterInventorySlotOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: blockedAdvertiserCategories, format, property
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.property) {
      throw new ValidationError("property is required");
    }
    if (!input.format) {
      throw new ValidationError("format is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (inventory domain)
    const entityId = this.idGenerator.invId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.slot.registerInventorySlot({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterInventorySlotOutput;
  }
}
