/**
 * ConversionDefinitionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConversionDefinitionRepository Port
 *
 * DDD: Application port for conversiondefinitionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DefineConversionActionInput, DefineConversionActionOutput } from "../dto/conversion-definition.dto";
export interface ConversionDefinitionRepository {
  defineConversionAction(input: DefineConversionActionInput): Promise<DefineConversionActionOutput>;
}

export type { DefineConversionActionInput, DefineConversionActionOutput } from "../dto/conversion-definition.dto";
