/**
 * PayoutPublisher Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PayoutPublisher Port
 *
 * DDD: Application port for payoutpublisher operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ExecutePublisherPayoutInput, ExecutePublisherPayoutOutput } from "../dto/payout.dto";
export interface PayoutPublisher {
  executePublisherPayout(input: ExecutePublisherPayoutInput): Promise<ExecutePublisherPayoutOutput>;
}

export type { ExecutePublisherPayoutInput, ExecutePublisherPayoutOutput } from "../dto/payout.dto";
