/**
 * GetCostPerAction DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reporting
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCostPerActionReportParams } from "@clearbid/core/reporting";

export function createGetCostPerActionRequest(overrides: Partial<GetCostPerActionReportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
