/**
 * GetConversionVerification handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getConversionVerification } from "@clearbid/api-server/domains/conversions/handlers";
import type { ConversionsDDDDependencies } from "@clearbid/api-server/domains/conversions";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@clearbid/tests/shared";
import { CONVERSIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetConversionVerification", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConversionsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConversionsDDDDependencies>(
      CONVERSIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetConversionVerification, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { conversionId: entity.id };

    await getConversionVerification(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetConversionVerification.execute).toHaveBeenCalledWith(expect.objectContaining({ conversionId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { conversionId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetConversionVerification, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getConversionVerification(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
