/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildBiddingDomainModule } from "./bidding/dependencies/bidding-ddd.dependencies.js";
export { buildCampaignsDomainModule } from "./campaigns/dependencies/campaigns-ddd.dependencies.js";
export { buildConversionsDomainModule } from "./conversions/dependencies/conversions-ddd.dependencies.js";
export { buildDisputesDomainModule } from "./disputes/dependencies/disputes-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildInventoryDomainModule } from "./inventory/dependencies/inventory-ddd.dependencies.js";
export { buildReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export { buildSettlementDomainModule } from "./settlement/dependencies/settlement-ddd.dependencies.js";

// Export all domain dependency types
export type { BiddingDomainModule } from "./bidding/dependencies/bidding-ddd.dependencies.js";
export type { CampaignsDomainModule } from "./campaigns/dependencies/campaigns-ddd.dependencies.js";
export type { ConversionsDomainModule } from "./conversions/dependencies/conversions-ddd.dependencies.js";
export type { DisputesDomainModule } from "./disputes/dependencies/disputes-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { InventoryDomainModule } from "./inventory/dependencies/inventory-ddd.dependencies.js";
export type { ReportingDomainModule } from "./reporting/dependencies/reporting-ddd.dependencies.js";
export type { SettlementDomainModule } from "./settlement/dependencies/settlement-ddd.dependencies.js";
