/**
 * ConversionDefinition Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { schemas } from "../schemas/campaigns.schemas.js";
/**
 * Entity: ConversionDefinitionEntity
 * Description: Represents the ConversionDefinition domain model.
 * Source: schemas.ConversionDefinition
 * Type: Domain Entity (API)
 */
export const ConversionDefinitionEntitySchema = schemas.ConversionDefinition;
