/**
 * Routes for ActionForecast
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getActionForecast } from "../handlers/action-forecast.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function actionForecastRoutes(fastify: FastifyInstance) {
  // GET /v1/campaigns/{campaignId}/action-forecast (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/campaigns/:campaignId/action-forecast",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { campaignId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBiddingDependenciesForRequest();
        await getActionForecast(request, reply, deps);
      });
    }
  );


}
