/**
 * Routes for BidRequest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { submitBidRequest } from "../handlers/bid-request.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function bidRequestRoutes(fastify: FastifyInstance) {
  // POST /v1/bid-requests (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/bid-requests",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getBiddingDependenciesForRequest();
        await submitBidRequest(request, reply, deps);
      });
    }
  );


}
