/**
 * Handlers for BidRequest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { BiddingDomainModule } from "../dependencies/bidding-ddd.dependencies.js";
import type { SubmitBidRequestInput } from "@clearbid/services/bidding";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/bid-requests
 * Operation: submitBidRequest
 */
export async function submitBidRequest(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: BiddingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SubmitBidRequestInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.bidRequests.create.execute(input);
  return reply.code(200).send(result);
}


