/**
 * StatementRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { StatementRepositoryDdb } from "./statement-repository.ddb.js";
/**
 * StatementRepositoryAdapter
 *
 * Implements StatementRepository port for infrastructure layer.
 */
export class StatementRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new StatementRepositoryDdb(this.dynamoClient);
    }
    async listSettlementStatements(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listSettlementStatements(input);
    }
    async getSettlementStatement(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getSettlementStatement(input);
    }
}
