/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@clearbid/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@clearbid/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@clearbid/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _bidding from "./bidding/index.js";
import * as _campaigns from "./campaigns/index.js";
import * as _conversions from "./conversions/index.js";
import * as _disputes from "./disputes/index.js";
import * as _identity from "./identity/index.js";
import * as _inventory from "./inventory/index.js";
import * as _reporting from "./reporting/index.js";
import * as _settlement from "./settlement/index.js";

// Export as namespaces
export const bidding = _bidding;
export const campaigns = _campaigns;
export const conversions = _conversions;
export const disputes = _disputes;
export const identity = _identity;
export const inventory = _inventory;
export const reporting = _reporting;
export const settlement = _settlement;
