/**
 * Disputes DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: disputes
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Disputes Domain Module - Composition root
 *
 * DDD: Composition root for disputes domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisputeRepositoryAdapter,
  ResolutionRepositoryAdapter,
} from "@clearbid/adapters/disputes";
import { getIdGeneratorService } from "@clearbid/adapters";
import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteListDisputes,
  ExecuteOpenDispute,
} from "@clearbid/services/disputes/usecases";
// Ports (interfaces)
import type {
  DisputeRepository,
  ResolutionRepository,
} from "@clearbid/services/disputes/ports";

export interface DisputesDomainModule {
  repos: {
    disputes: DisputeRepository;
    resolutions: ResolutionRepository;
  };
  useCases: {
    disputes: {
      get: ExecuteOpenDispute;
      list: ExecuteListDisputes;
    };
  };
}

export function buildDisputesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): DisputesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disputes?: DisputeRepository;
      resolutions?: ResolutionRepository;
    } = {};

    obj.disputes = new DisputeRepositoryAdapter(dynamoClient);
    obj.resolutions = new ResolutionRepositoryAdapter(dynamoClient);
    return {
      disputes: obj.disputes!,
      resolutions: obj.resolutions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disputes: {
      get: new ExecuteOpenDispute(executionContext, idGenerator, repos.disputes),
      list: new ExecuteListDisputes(executionContext, idGenerator, repos.disputes),
    },
  };
  return { repos, useCases: useCases as DisputesDomainModule["useCases"] };
}
