/**
 * QuarantineInventorySlot handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { quarantineInventorySlot } from "@clearbid/api-server/domains/inventory/handlers";
import type { InventoryDDDDependencies } from "@clearbid/api-server/domains/inventory";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@clearbid/tests/shared";
import { INVENTORY_USE_CASES } from "../__factories__/use-cases.js";

describe("QuarantineInventorySlot", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InventoryDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InventoryDDDDependencies>(
      INVENTORY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeQuarantineInventorySlot, "execute").mockResolvedValue(useCaseResult);

    await quarantineInventorySlot(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeQuarantineInventorySlot.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
