/**
 * Handlers for Payout
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: settlement
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SettlementDomainModule } from "../dependencies/settlement-ddd.dependencies.js";
import type { ExecutePublisherPayoutInput } from "@clearbid/services/settlement";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/settlement/payouts
 * Operation: executePublisherPayout
 */
export async function executePublisherPayout(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SettlementDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExecutePublisherPayoutInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.payouts.create.execute(input);
  return reply.code(201).send(result);
}


