/**
 * ExecuteAttestConversion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAttestConversion Use Case
 *
 * DDD: Application use case for get Conversion.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AttestConversionInput, AttestConversionOutput } from "../dto/conversion.dto";
import type { ExecutionContextService, IdGeneratorService } from "@clearbid/services/_shared/index.js";
import type { ConversionRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteAttestConversion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly conversion: ConversionRepository
  ) {}

  async execute(input: AttestConversionInput): Promise<AttestConversionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.cnvId();

    // All field names extracted from OpenAPI spec: actionType, attributionToken, externalReference, occurredAt
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.conversion.attestConversion({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as AttestConversionOutput;
  }
}
