/**
 * CampaignRepository - DynamoDB Implementation
 *
 * Generated by DynamoDB Repository Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export class CampaignRepositoryDdb {
    dynamoClient;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
    }
    async listCampaigns(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
    async createCampaign(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
    async getCampaign(input) {
        // TODO: Implement using x-dynamodb metadata
        throw new Error("Not implemented - missing x-dynamodb metadata");
    }
}
