/**
 * CampaignRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { CampaignRepositoryDdb } from "./campaign-repository.ddb.js";
/**
 * CampaignRepositoryAdapter
 *
 * Implements CampaignRepository port for infrastructure layer.
 */
export class CampaignRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new CampaignRepositoryDdb(this.dynamoClient);
    }
    async listCampaigns(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listCampaigns(input);
    }
    async createCampaign(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.createCampaign(input);
    }
    async getCampaign(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.getCampaign(input);
    }
}
