/**
 * ConversionDefinitionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConversionDefinitionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConversionDefinitionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConversionDefinitionRepository,
} from "@clearbid/services/campaigns";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConversionDefinitionRepositoryDdb } from "./conversion-definition-repository.ddb.js";

/**
 * ConversionDefinitionRepositoryAdapter
 *
 * Implements ConversionDefinitionRepository port for infrastructure layer.
 */
export class ConversionDefinitionRepositoryAdapter implements ConversionDefinitionRepository {
  private readonly ddb: ConversionDefinitionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConversionDefinitionRepositoryDdb(this.dynamoClient);
  }

  async defineConversionAction(input: Parameters<ConversionDefinitionRepository['defineConversionAction']>[0]): Promise<Awaited<ReturnType<ConversionDefinitionRepository['defineConversionAction']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.defineConversionAction(input);
  }
}
