/**
 * ConversionDefinitionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: campaigns
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { ConversionDefinitionRepositoryDdb } from "./conversion-definition-repository.ddb.js";
/**
 * ConversionDefinitionRepositoryAdapter
 *
 * Implements ConversionDefinitionRepository port for infrastructure layer.
 */
export class ConversionDefinitionRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new ConversionDefinitionRepositoryDdb(this.dynamoClient);
    }
    async defineConversionAction(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.defineConversionAction(input);
    }
}
