/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
export * from "./quarantine-repository.ddb.js";
export * from "./slot-repository.ddb.js";
export * from "./quarantine-repository.adapter.js";
export * from "./slot-repository.adapter.js";
