/**
 * QuarantineRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { QuarantineRepositoryDdb } from "./quarantine-repository.ddb.js";
/**
 * QuarantineRepositoryAdapter
 *
 * Implements QuarantineRepository port for infrastructure layer.
 */
export class QuarantineRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new QuarantineRepositoryDdb(this.dynamoClient);
    }
    async quarantineInventorySlot(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.quarantineInventorySlot(input);
    }
}
