/**
 * SlotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlotRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SlotRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SlotRepository,
} from "@clearbid/services/inventory";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SlotRepositoryDdb } from "./slot-repository.ddb.js";

/**
 * SlotRepositoryAdapter
 *
 * Implements SlotRepository port for infrastructure layer.
 */
export class SlotRepositoryAdapter implements SlotRepository {
  private readonly ddb: SlotRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SlotRepositoryDdb(this.dynamoClient);
  }

  async listInventorySlots(input: Parameters<SlotRepository['listInventorySlots']>[0]): Promise<Awaited<ReturnType<SlotRepository['listInventorySlots']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listInventorySlots(input);
  }

  async registerInventorySlot(input: Parameters<SlotRepository['registerInventorySlot']>[0]): Promise<Awaited<ReturnType<SlotRepository['registerInventorySlot']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerInventorySlot(input);
  }
}
