/**
 * SlotRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */
import { SlotRepositoryDdb } from "./slot-repository.ddb.js";
/**
 * SlotRepositoryAdapter
 *
 * Implements SlotRepository port for infrastructure layer.
 */
export class SlotRepositoryAdapter {
    dynamoClient;
    ddb;
    constructor(dynamoClient) {
        this.dynamoClient = dynamoClient;
        this.ddb = new SlotRepositoryDdb(this.dynamoClient);
    }
    async listInventorySlots(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.listInventorySlots(input);
    }
    async registerInventorySlot(input) {
        // Delegate to DynamoDB repository
        return await this.ddb.registerInventorySlot(input);
    }
}
