/**
 * GetActionForecast DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetActionForecastParams } from "@clearbid/core/bidding";

export function createGetActionForecastRequest(overrides: Partial<GetActionForecastParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
