/**
 * Handlers for Verification
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ConversionsDomainModule } from "../dependencies/conversions-ddd.dependencies.js";
import type { GetConversionVerificationInput } from "@clearbid/services/conversions";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/conversions/{conversionId}/verification
 * Operation: getConversionVerification
 */
export async function getConversionVerification(
  request: FastifyRequest<{ Params: { conversionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ConversionsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetConversionVerificationInput = {
    conversionId: request.params.conversionId,
  };
  const result = await deps.useCases.verifications.get.execute(input);
  return reply.code(200).send(result);
}


