/**
 * ConversionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConversionRepository Port
 *
 * DDD: Application port for conversionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AttestConversionInput, AttestConversionOutput, ListConversionsInput, ListConversionsOutput } from "../dto/conversion.dto";
export interface ConversionRepository {
  listConversions(input: ListConversionsInput): Promise<ListConversionsOutput>;
  attestConversion(input: AttestConversionInput): Promise<AttestConversionOutput>;
}

export type { AttestConversionInput, AttestConversionOutput, ListConversionsInput, ListConversionsOutput } from "../dto/conversion.dto";
