/**
 * VerificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VerificationRepository Port
 *
 * DDD: Application port for verificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetConversionVerificationInput, GetConversionVerificationOutput } from "../dto/verification.dto";
export interface VerificationRepository {
  getConversionVerification(input: GetConversionVerificationInput): Promise<GetConversionVerificationOutput>;
}

export type { GetConversionVerificationInput, GetConversionVerificationOutput } from "../dto/verification.dto";
