/**
 * ActionForecastRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ActionForecastRepository Port
 *
 * DDD: Application port for actionforecastrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetActionForecastInput, GetActionForecastOutput } from "../dto/action-forecast.dto";
export interface ActionForecastRepository {
  getActionForecast(input: GetActionForecastInput): Promise<GetActionForecastOutput>;
}

export type { GetActionForecastInput, GetActionForecastOutput } from "../dto/action-forecast.dto";
