/**
 * BidRequestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: bidding
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BidRequestRepository Port
 *
 * DDD: Application port for bidrequestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SubmitBidRequestInput, SubmitBidRequestOutput } from "../dto/bid-request.dto";
export interface BidRequestRepository {
  submitBidRequest(input: SubmitBidRequestInput): Promise<SubmitBidRequestOutput>;
}

export type { SubmitBidRequestInput, SubmitBidRequestOutput } from "../dto/bid-request.dto";
