/**
 * Conversions DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: conversions
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Conversions Domain Module - Composition root
 *
 * DDD: Composition root for conversions domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConversionRepositoryAdapter,
  VerificationRepositoryAdapter,
} from "@clearbid/adapters/conversions";
import { getIdGeneratorService } from "@clearbid/adapters";
import type { AdapterDynamoDBClient } from "@clearbid/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAttestConversion,
  ExecuteListConversions,
} from "@clearbid/services/conversions/usecases";
// Ports (interfaces)
import type {
  ConversionRepository,
  VerificationRepository,
} from "@clearbid/services/conversions/ports";

export interface ConversionsDomainModule {
  repos: {
    conversions: ConversionRepository;
    verifications: VerificationRepository;
  };
  useCases: {
    conversions: {
      get: ExecuteAttestConversion;
      list: ExecuteListConversions;
    };
  };
}

export function buildConversionsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ConversionsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      conversions?: ConversionRepository;
      verifications?: VerificationRepository;
    } = {};

    obj.conversions = new ConversionRepositoryAdapter(dynamoClient);
    obj.verifications = new VerificationRepositoryAdapter(dynamoClient);
    return {
      conversions: obj.conversions!,
      verifications: obj.verifications!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    conversions: {
      get: new ExecuteAttestConversion(executionContext, idGenerator, repos.conversions),
      list: new ExecuteListConversions(executionContext, idGenerator, repos.conversions),
    },
  };
  return { repos, useCases: useCases as ConversionsDomainModule["useCases"] };
}
