/**
 * QuarantineRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QuarantineRepository Port
 *
 * DDD: Application port for quarantinerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { QuarantineInventorySlotInput, QuarantineInventorySlotOutput } from "../dto/quarantine.dto";
export interface QuarantineRepository {
  quarantineInventorySlot(input: QuarantineInventorySlotInput): Promise<QuarantineInventorySlotOutput>;
}

export type { QuarantineInventorySlotInput, QuarantineInventorySlotOutput } from "../dto/quarantine.dto";
