/**
 * SlotRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: inventory
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SlotRepository Port
 *
 * DDD: Application port for slotrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListInventorySlotsInput, ListInventorySlotsOutput, RegisterInventorySlotInput, RegisterInventorySlotOutput } from "../dto/slot.dto";
export interface SlotRepository {
  listInventorySlots(input: ListInventorySlotsInput): Promise<ListInventorySlotsOutput>;
  registerInventorySlot(input: RegisterInventorySlotInput): Promise<RegisterInventorySlotOutput>;
}

export type { ListInventorySlotsInput, ListInventorySlotsOutput, RegisterInventorySlotInput, RegisterInventorySlotOutput } from "../dto/slot.dto";
